# Generated by Django 5.1 on 2024-08-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementcommande',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='elementcommande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='elementpanier',
            name='panier',
        ),
        migrations.RemoveField(
            model_name='elementpanier',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='recherche',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Avis',
        ),
        migrations.DeleteModel(
            name='ElementCommande',
        ),
        migrations.DeleteModel(
            name='ElementPanier',
        ),
        migrations.DeleteModel(
            name='Livraison',
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
        migrations.DeleteModel(
            name='Recherche',
        ),
    ]
