# Generated by Django 5.1 on 2024-09-04 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_shop', '0004_alter_panier_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='produits',
            field=models.ManyToManyField(through='E_shop.LignePanier', to='E_shop.produit'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
